#%RAML 1.0 DataType


    type: object
    properties:
      message:
        required: true
        type: string
        example:
          "303-3966782"
      transactionId:
        required: true
        type: string
        example:
          "303-3966782"
      gateway:
        required: true
        type: string
        example:
          "303-3463789"
      entityCode:
        required: true
        type: string
        example:
          "LHK"     
      cardType:
        required: true
        type: string  
        example: 
          "234-6567893"   
      coBrandFlag:
        required: true
        type: string
        example:
          "346-2836338"
      serviceChargeRate:
        required: true
        type: string
        example: 
          "673-4562797"
      returnUrl:
        required: true
        type: string
        example:
              "abc.com/returnUrl" 
      cancelUrl:
        required: true
        type: string
        example:
                "abc.com/cancelUrl"
      version:
        required: true
        type: string
        example: "a53gj754hj"                         
                                                  
