http:
  host: "0.0.0.0"
  port: "8081"
  
db:
  host: bsgb50hmuqcx3qmx8bfe-mysql.services.clever-cloud.com
  port: 3306
  user: uyyojtjk48zokvq2
  password: pCtDKY8gnncv1Va6nHLh 
  database: bsgb50hmuqcx3qmx8bfe