#%RAML 1.0 Trait

headers:
  msgid:
    required: true
    type: string
    minLength: 36
    maxLength: 36
  clientId:
    required: true
    type: string
    example: "acdfdsfghjk"
  clientSecret:
    required: true
    type: string
    example: "acdfdsfghjk"
          